version: "3.9"

services:
  db:
    image: postgres:15
    container_name: school_db
    environment:
      POSTGRES_USER: schooluser
      POSTGRES_PASSWORD: schoolpass
      POSTGRES_DB: schooldb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - school_network

  redis:
    image: redis:7
    container_name: school_redis
    networks:
      - school_network

  web:
    build:
      context: ../SchoolProject
      dockerfile: ../infra/Dockerfile
    container_name: school_web
    command: >
      sh -c "./infra/wait-for-db.sh db py manage.py migrate &&
             py manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../SchoolProject:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev
      - POSTGRES_DB=schooldb
      - POSTGRES_USER=schooluser
      - POSTGRES_PASSWORD=schoolpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - school_network

  celery:
    build:
      context: ../SchoolProject
      dockerfile: ../infra/Dockerfile
    container_name: school_celery
    command: sh -c "./infra/wait-for-db.sh db celery -A SchoolProject worker -l info"
    volumes:
      - ../SchoolProject:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev
      - POSTGRES_DB=schooldb
      - POSTGRES_USER=schooluser
      - POSTGRES_PASSWORD=schoolpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - school_network

networks:
  school_network:
    driver: bridge

volumes:
  db_data:
